apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    metadata:
      labels:
       name: my-app-pod
    spec:
      containers:
        - name: my-app-container
          image: aocampos/my-app:latest
          ports:
            - containerPort: 8080